# Generated by Django 6.0 on 2025-12-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
