# Generated by Django 6.0 on 2025-12-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0002_alter_normaluser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='role',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='mobile',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
