# Generated by Django 6.0 on 2025-12-31 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('normal_user', '0003_normaluser_role_alter_normaluser_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaluser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='normaluser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Kaun ne delete kiya (admin/user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='mobile',
            field=models.CharField(db_index=True, help_text='Mobile number (e.g., +91 format bhi accept kar sakta hai)', max_length=15, unique=True),
        ),
        migrations.AddIndex(
            model_name='normaluser',
            index=models.Index(fields=['email'], name='normal_user_email_dcb66b_idx'),
        ),
        migrations.AddIndex(
            model_name='normaluser',
            index=models.Index(fields=['mobile'], name='normal_user_mobile_996c32_idx'),
        ),
        migrations.AddIndex(
            model_name='normaluser',
            index=models.Index(fields=['role'], name='normal_user_role_8c54ef_idx'),
        ),
        migrations.AddIndex(
            model_name='normaluser',
            index=models.Index(fields=['is_deleted'], name='normal_user_is_dele_0cbf8b_idx'),
        ),
        migrations.AddIndex(
            model_name='normaluser',
            index=models.Index(fields=['is_active'], name='normal_user_is_acti_16e94c_idx'),
        ),
        migrations.AddIndex(
            model_name='normaluser',
            index=models.Index(fields=['deleted_at'], name='normal_user_deleted_036e79_idx'),
        ),
    ]
