# Generated by Django 6.0 on 2025-12-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0004_alter_normaluser_options_normaluser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='normaluser',
            managers=[
            ],
        ),
    ]
