# Generated by Django 6.0 on 2025-12-31 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0005_alter_normaluser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='mobile',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
