# Generated by Django 6.0 on 2026-01-07 09:56

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0006_alter_normaluser_deleted_by_alter_normaluser_mobile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='normaluser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
