# Generated by Django 6.0 on 2026-01-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('GUEST', 'Independent User')], default='GUEST', max_length=20),
        ),
    ]
