# Generated by Django 6.0 on 2026-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0009_alter_normaluser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='admin_custom_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='mobile',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
