# Generated by Django 6.0 on 2026-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('normal_user', '0010_normaluser_admin_custom_id_alter_normaluser_mobile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='normaluser',
            name='normal_user_email_dcb66b_idx',
        ),
        migrations.RemoveIndex(
            model_name='normaluser',
            name='normal_user_mobile_996c32_idx',
        ),
        migrations.RemoveIndex(
            model_name='normaluser',
            name='normal_user_is_dele_0cbf8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='normaluser',
            name='normal_user_is_acti_16e94c_idx',
        ),
        migrations.RemoveIndex(
            model_name='normaluser',
            name='normal_user_deleted_036e79_idx',
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='normaluser',
            index=models.Index(fields=['is_deleted', 'is_active'], name='normal_user_is_dele_59d31b_idx'),
        ),
    ]
