# Generated by Django 6.0 on 2026-01-23 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('students_classroom', '0004_standard_organization_alter_standard_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='students_classroom.standard'),
        ),
    ]
