# Generated by Django 6.0 on 2026-02-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_admin_alter_organization_pincode_and_more'),
        ('students', '0002_studentprofile_current_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Jis din asliyat mein payment received hui', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_unique_id',
            field=models.CharField(db_index=True, help_text='Roll number or admission number', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('organization', 'student_unique_id')},
        ),
    ]
