# Generated by Django 6.0 on 2026-01-19 05:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name; used in URLs like /org/my-school/', max_length=255, unique=True, verbose_name='Slug (URL-friendly)')),
                ('org_id', models.CharField(blank=True, help_text='e.g. SCH-DEL-2026-001', max_length=50, unique=True, verbose_name='Official Organization ID')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Registration / Affiliation Number')),
                ('org_type', models.CharField(choices=[('school', 'School'), ('coaching', 'Coaching / Tuition Center'), ('college', 'College / University'), ('academy', 'Academy / Training Institute'), ('online_platform', 'Online Education Platform'), ('other', 'Other')], default='school', max_length=50, verbose_name='Organization Type')),
                ('affiliation_board', models.CharField(blank=True, max_length=100, verbose_name='Affiliation Board / Curriculum')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/%Y/%m/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='About / Description')),
                ('address', models.TextField(blank=True, verbose_name='Full Address')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')], verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Official Contact Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Established Year')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active on Platform')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by Platform')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Internal Verification Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organization', to=settings.AUTH_USER_MODEL, verbose_name='Organization Admin / Owner')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Principal/Owner', help_text='e.g. Principal, Owner, Vice Principal, Administrator, Academic Head', max_length=100, verbose_name='Designation')),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, this admin loses access without deleting the record', verbose_name='Is Active')),
                ('can_modify_settings', models.BooleanField(default=True, help_text='School name, address, logo, session/year, timetable structure etc.', verbose_name='Can modify school settings')),
                ('can_manage_staff', models.BooleanField(default=True, verbose_name='Can manage teachers & non-teaching staff')),
                ('can_manage_students', models.BooleanField(default=True, verbose_name='Can manage students & admissions')),
                ('can_view_finances', models.BooleanField(default=False, help_text='Usually restricted to Owner / Accountant level', verbose_name='Can view fee & financial data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_admins', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_admins', to='organizations.organization', verbose_name='School / Branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'School Admin',
                'verbose_name_plural': 'School Admins',
                'permissions': [('can_change_school_core_settings', 'Can change core school configuration'), ('can_manage_fee_structure', 'Can create/edit fee heads & structures'), ('can_approve_financial_transactions', 'Can approve fee receipts/refunds'), ('can_generate_admin_reports', 'Can generate school-wide reports')],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_048085_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_id'], name='organizatio_org_id_b3d4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type'], name='organizatio_org_typ_ac5ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='schooladmin',
            index=models.Index(fields=['user', 'organization'], name='organizatio_user_id_6b57f1_idx'),
        ),
        migrations.AddIndex(
            model_name='schooladmin',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_75ea51_idx'),
        ),
        migrations.AddIndex(
            model_name='schooladmin',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_e64f4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schooladmin',
            unique_together={('user', 'organization')},
        ),
    ]
