# Generated by Django 6.0 on 2026-01-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, help_text='e.g. Agra, Delhi, Mumbai', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='organization',
            name='fee_category',
            field=models.CharField(blank=True, choices=[('budget', 'Budget Friendly'), ('mid_range', 'Mid-Range'), ('premium', 'Premium / High-End')], max_length=20, null=True, verbose_name='Fee Category'),
        ),
        migrations.AddField(
            model_name='organization',
            name='gender_type',
            field=models.CharField(choices=[('coed', 'Co-Ed'), ('boys', 'Boys Only'), ('girls', 'Girls Only')], default='coed', max_length=20, verbose_name='Gender Type'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_hostel',
            field=models.BooleanField(default=False, verbose_name='Hostel Facility'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='Library'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_playground',
            field=models.BooleanField(default=False, verbose_name='Playground'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_smart_class',
            field=models.BooleanField(default=False, verbose_name='Smart Classes'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_transport',
            field=models.BooleanField(default=False, verbose_name='Transport Facility'),
        ),
        migrations.AddField(
            model_name='organization',
            name='instruction_medium',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('bilingual', 'Bilingual/Both')], default='english', max_length=20, verbose_name='Medium of Instruction'),
        ),
        migrations.AddField(
            model_name='organization',
            name='locality',
            field=models.CharField(blank=True, help_text='e.g. Sanjay Place, Civil Lines', max_length=255, null=True, verbose_name='Locality / Area'),
        ),
        migrations.AddField(
            model_name='organization',
            name='monthly_fees_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Approx Min Monthly Fee'),
        ),
        migrations.AddField(
            model_name='organization',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pincode'),
        ),
    ]
