# Generated by Django 6.0 on 2026-01-19 05:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('bio', models.TextField(blank=True, max_length=2000, verbose_name='Professional Bio')),
                ('qualifications', models.TextField(verbose_name='Qualifications & Certifications')),
                ('experience_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Years of Experience')),
                ('subject_expertise', models.JSONField(blank=True, default=dict, help_text="Example: {'primary': 'Mathematics', 'secondary': ['Physics', 'Chemistry'], 'levels': ['9-10', '11-12'], 'boards': ['CBSE', 'ICSE']}", verbose_name='Subject Expertise')),
                ('languages_spoken', models.JSONField(blank=True, default=list, help_text="List like ['English', 'Hindi', 'Punjabi']", verbose_name='Languages Spoken')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by Platform')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Internal Notes')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/%Y/%m/', verbose_name='Profile Picture')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(100.0)], verbose_name='Hourly Rate (INR)')),
                ('preferred_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Both')], default='online', max_length=20, verbose_name='Preferred Teaching Mode')),
                ('service_areas', models.JSONField(blank=True, default=list, help_text="e.g. ['Delhi', 'Noida', 'Gurgaon'] or pincodes", verbose_name='Service Areas (for offline)')),
                ('is_active_teacher', models.BooleanField(default=True, verbose_name='Active on Platform')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason (if not verified)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='organizations.organization', verbose_name='Affiliated School/Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='teachers_te_organiz_d4b537_idx'), models.Index(fields=['is_verified'], name='teachers_te_is_veri_e70801_idx'), models.Index(fields=['is_active_teacher'], name='teachers_te_is_acti_485e73_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('experience_years__gte', 0)), name='experience_non_negative')],
            },
        ),
    ]
