# Generated by Django 6.0 on 2026-01-19 05:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='International format use karein, e.g. +919876543210', max_length=128, null=True, region=None, unique=True, verbose_name='Phone Number')),
                ('relation', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Legal Guardian'), ('OTHER', 'Other')], default='FATHER', max_length=20, verbose_name='Relation to Child')),
                ('address', models.TextField(blank=True, verbose_name='Home Address')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, related_name='parents', to='students.studentprofile', verbose_name='Children')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Link Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='parents.parentprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Parent Student Link',
                'verbose_name_plural': 'Parent Student Links',
            },
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['phone_number'], name='parents_par_phone_n_a954b2_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['is_active'], name='parents_par_is_acti_3d875d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentstudentlink',
            unique_together={('parent', 'student')},
        ),
    ]
