# Generated by Django 6.0 on 2026-01-19 05:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Class 8, Grade 10, STD XII', max_length=50, unique=True, verbose_name='Standard / Grade')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Standard',
                'verbose_name_plural': 'Standards',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='students_cl_is_acti_b0599a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassroomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(db_index=True, editable=False, max_length=10, unique=True, verbose_name='Session Code')),
                ('title', models.CharField(blank=True, help_text='e.g. Science Marathon, Algebra Crash Course', max_length=120, verbose_name='Session Title (optional)')),
                ('student_limit', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Students')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULL', 'Full'), ('EXPIRED', 'Expired'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10, verbose_name='Status')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Leave empty for independent / personal classes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_sessions', to='organizations.organization', verbose_name='Organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_sessions', to='teachers.teacher', verbose_name='Teacher')),
                ('target_standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_sessions', to='students_classroom.standard', verbose_name='Target Standard')),
            ],
            options={
                'verbose_name': 'Classroom Session',
                'verbose_name_plural': 'Classroom Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to='teachers.teacher')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='students_classroom.classroomsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Join Request',
                'verbose_name_plural': 'Join Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='students_cl_session_7dbcef_idx'), models.Index(fields=['user', 'status'], name='students_cl_user_id_0aca4b_idx')],
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SessionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students_classroom.classroomsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_enrollments', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'indexes': [models.Index(fields=['student', 'is_active'], name='students_cl_student_f24f8f_idx'), models.Index(fields=['session', 'is_active'], name='students_cl_session_34a7f3_idx')],
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.AddIndex(
            model_name='classroomsession',
            index=models.Index(fields=['session_code', 'status'], name='students_cl_session_f4331e_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomsession',
            index=models.Index(fields=['teacher', 'status', 'expires_at'], name='students_cl_teacher_3db084_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomsession',
            index=models.Index(fields=['organization', 'status'], name='students_cl_organiz_7b4c7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomsession',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='session_expires_after_creation'),
        ),
    ]
