# Generated by Django 6.0 on 2026-01-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_classroom', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomsession',
            name='purpose',
            field=models.CharField(choices=[('STUDENT', 'Student Admission'), ('TEACHER', 'Teacher Recruitment')], db_index=True, default='STUDENT', max_length=10, verbose_name='Session Purpose'),
        ),
        migrations.AlterField(
            model_name='classroomsession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_sessions', to='teachers.teacher', verbose_name='Teacher'),
        ),
    ]
