# Generated by Django 6.0 on 2026-01-22 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_classroom', '0002_classroomsession_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsession',
            name='target_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='students_classroom.standard', verbose_name='Target Standard'),
        ),
    ]
