# Generated by Django 6.0 on 2026-01-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_city_organization_fee_category_and_more'),
        ('students_classroom', '0003_alter_classroomsession_target_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='name',
            field=models.CharField(help_text='e.g. Class 8, Grade 10, STD XII', max_length=50, verbose_name='Standard / Grade'),
        ),
        migrations.AlterUniqueTogether(
            name='standard',
            unique_together={('organization', 'name')},
        ),
    ]
