# Generated by Django 6.0 on 2026-01-23 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_classroom', '0004_standard_organization_alter_standard_name_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_standards', to='teachers.teacher', verbose_name='Class Teacher'),
        ),
    ]
