# Generated by Django 6.0 on 2026-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_admin_alter_organization_pincode_and_more'),
        ('students_classroom', '0005_standard_class_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='standard',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterUniqueTogether(
            name='standard',
            unique_together={('organization', 'name', 'section')},
        ),
    ]
