# Generated by Django 6.0 on 2026-02-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_classroom', '0006_alter_standard_unique_together_standard_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomsession',
            name='is_deleted',
        ),
    ]
